// apps/web-nuxt/pages/admin/artigos/new.vue
<script setup lang="ts">
import ArticleEditor from "~/components/admin/ArticleEditor.vue";

definePageMeta({ layout: "admin", middleware: ["admin"] });

useHead({
  title: "Criar Artigo - Admin Astrobiologia",
  meta: [{ name: "robots", content: "noindex, nofollow" }],
});

const localePath = useLocalePath();
const saving = ref(false);

async function handleSave(
  articleData: Record<string, unknown>,
  translations: Array<Record<string, unknown>>
) {
  saving.value = true;
  try {
    await $fetch("/api/admin/articles/create", {
      method: "POST",
      body: {
        ...articleData,
        translations,
      },
    });
    await navigateTo(localePath("/admin/artigos"));
  } catch (err: unknown) {
    const msg =
      err &&
      typeof err === "object" &&
      "data" in err &&
      typeof (err as { data?: { statusMessage?: string } }).data
        ?.statusMessage === "string"
        ? (err as { data: { statusMessage: string } }).data.statusMessage
        : "Erro ao criar artigo.";
    alert(msg);
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <div class="mb-8">
    <h1 class="text-3xl font-black text-slate-900 uppercase tracking-tight">
      Criar Novo Artigo
    </h1>
    <p
      class="text-slate-500 mt-2 text-sm font-medium uppercase tracking-widest"
    >
      Inicie um novo conteúdo científico
    </p>
  </div>

  <ArticleEditor
    :article="null"
    :translations="[]"
    :saving="saving"
    @save="handleSave"
  />
</template>

// src/routes/admin/artigos/new/+page.svelte
<script lang="ts">
	import { deserialize } from '$app/forms';
	import { goto } from '$app/navigation';
	import ArticleEditor from '$lib/components/ArticleEditor.svelte';

	let isLoading = $state(false);

	async function saveArticle(articleData: any, translations: any[]) {
		isLoading = true;

		try {
            const formData = new FormData();
            formData.append('articleData', JSON.stringify(articleData));
            formData.append('translations', JSON.stringify(translations));

            const response = await fetch('?/save', {
                method: 'POST',
                body: formData
            });

            const result = deserialize(await response.text());

            if (result.type === 'success') {
                await goto('/admin/artigos');
            } else if (result.type === 'failure' || result.type === 'error') {
                const errorMessage = (result as any).data?.error || (result as any).error?.message || 'Erro ao salvar';
                alert(errorMessage);
            }
		} catch (err) {
			console.error('Error saving article:', err);
			alert('Erro inesperado ao salvar.');
		} finally {
			isLoading = false;
		}
	}
</script>

<svelte:head>
	<title>Criar Artigo - Admin Astrobiologia</title>
	<meta name="robots" content="noindex, nofollow" />
</svelte:head>

<div class="mb-8">
	<h1 class="text-3xl font-black text-slate-900 uppercase tracking-tight">Criar Novo Artigo</h1>
	<p class="text-slate-500 mt-2 text-sm font-medium uppercase tracking-widest">Inicie um novo conteúdo científico</p>
</div>

<ArticleEditor bind:isLoading={isLoading} onSave={saveArticle} />
