// src/routes/artigos/[slug]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { formatDate, readingTime } from '$lib/utils';
	import { CATEGORIES, getImageUrl } from '$lib/appwrite';
	import { Clock, Share2, Calendar } from 'lucide-svelte';
	import { getLocale } from '$lib/paraglide/runtime';

	import { generateSchemaMarkup } from '$lib/seo';

	let { data }: { data: PageData } = $props();
	const { article, relatedArticles } = data;

	// Use translation data if available, fallback to master (legacy support)
	const title = $derived(article.translation?.title || (article as any).title);
	const slug = $derived(article.translation?.slug || (article as any).slug);
	const excerpt = $derived(article.translation?.excerpt || (article as any).excerpt);
	const content = $derived(article.translation?.content || (article as any).content || '');
	const lang = $derived(getLocale());

	const category = $derived(CATEGORIES.find(c => c.slug === article.category));
	const imageUrl = $derived(article.featuredImage 
		? (article.featuredImage.startsWith('http') 
			? article.featuredImage 
			: `${getImageUrl(article.featuredImage, 1200, 630)}&output=webp&quality=85`) 
		: null);
</script>

<svelte:head>
	<title>{title} - Astrobiologia.com.br</title>
	<meta name="description" content={excerpt} />
	<link rel="canonical" href="https://astrobiologia.com.br/{lang}/artigos/{slug}" />
	
	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="article" />
	<meta property="og:url" content="https://astrobiologia.com.br/{lang}/artigos/{slug}" />
	<meta property="og:title" content={title} />
	<meta property="og:description" content={excerpt} />
	{#if imageUrl}
		<meta property="og:image" content={imageUrl} />
		<meta property="og:image:width" content="1200" />
		<meta property="og:image:height" content="630" />
	{/if}
	<meta property="article:published_time" content={article.publishedAt || article.$createdAt} />
	<meta property="article:author" content={article.authorName || 'Danilo Albergaria'} />
	<meta property="article:section" content={category?.name || 'Astrobiologia'} />
</svelte:head>

<main class="min-h-screen bg-background">
	<!-- Page Header -->
	<div class="relative overflow-hidden pt-32 pb-16 md:pt-48 md:pb-24 border-b border-slate-100 bg-white">
		<div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
			{#if category}
				<a href="/{lang}/categorias/{article.category}" class="inline-block text-primary text-xs font-black uppercase tracking-[0.2em] mb-8 hover:underline">
					{category.name}
				</a>
			{/if}
			
			<h1 class="text-4xl md:text-6xl lg:text-7xl font-black text-slate-900 leading-[1.05] mb-10 text-balance font-sans tracking-tight">
				{title}
			</h1>
			
			<p class="text-xl md:text-2xl text-slate-600 leading-relaxed mb-12 font-serif text-balance italic">
				{excerpt}
			</p>
			
			<div class="flex flex-wrap items-center gap-8 text-slate-400 text-[10px] font-black uppercase tracking-widest border-t border-slate-100 pt-8">
				<div class="flex items-center gap-3">
					<div class="h-8 w-8 rounded-full bg-accent text-white flex items-center justify-center font-bold">
						{article.authorName?.charAt(0) || 'D'}
					</div>
					<div class="text-slate-900">{article.authorName || 'Danilo Albergaria'}</div>
				</div>
				<div class="flex items-center gap-2">
					<Calendar class="h-3.5 w-3.5" />
					{formatDate(article.publishedAt || article.$createdAt)}
				</div>
				<div class="flex items-center gap-2">
					<Clock class="h-3.5 w-3.5" />
					{readingTime(content)} min de leitura
				</div>
			</div>
		</div>
	</div>

	<!-- Featured Image -->
	{#if imageUrl}
		<div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-12">
			<figure>
				<div class="aspect-[16/9] overflow-hidden bg-slate-100">
					<img
						src={imageUrl}
						alt={article.featuredImageAlt || title}
						class="w-full h-full object-cover"
						fetchpriority="high"
					/>
				</div>
				{#if article.featuredImageAlt}
					<figcaption class="mt-4 text-center text-slate-500 text-sm italic font-serif">
						{article.featuredImageAlt}
					</figcaption>
				{/if}
			</figure>
		</div>
	{/if}

	<!-- Content -->
	<article class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-12 md:py-24">
		<div class="prose prose-astro max-w-none">
			{@html content}
		</div>

		<!-- Footer Meta -->
		<div class="mt-24 pt-12 border-t border-slate-100 flex flex-col md:flex-row md:items-center justify-between gap-8">
			{#if article.tags && article.tags.length > 0}
				<div class="flex flex-wrap gap-3">
					{#each article.tags as tag}
						<span class="px-3 py-1 bg-slate-100 text-slate-600 text-[10px] font-bold uppercase tracking-widest">
							#{tag}
						</span>
					{/each}
				</div>
			{/if}
			
			<div class="flex items-center gap-6">
				<button 
					onclick={() => {
						if (navigator.share) {
							navigator.share({
								title,
								text: excerpt,
								url: window.location.href
							});
						}
					}}
					class="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-primary transition-colors"
				>
					<Share2 class="h-4 w-4" />
					Compartilhar
				</button>
			</div>
		</div>
	</article>

	<!-- Related Articles -->
	{#if relatedArticles && relatedArticles.length > 0}
		<section class="bg-slate-50 border-t border-slate-100 py-24">
			<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
				<h2 class="text-[10px] font-black uppercase tracking-[0.3em] text-slate-400 mb-16 text-center">Continue Explorando</h2>
				<div class="grid grid-cols-1 md:grid-cols-3 gap-12">
					{#each relatedArticles as related}
						{@const rTitle = related.translation?.title || (related as any).title}
						{@const rSlug = related.translation?.slug || (related as any).slug}
						{@const rExcerpt = related.translation?.excerpt || (related as any).excerpt}
						<div class="flex flex-col h-full bg-white border border-slate-100 hover:shadow-xl transition-all duration-300">
							<a
								href="/{lang}/artigos/{rSlug}"
								class="block overflow-hidden aspect-[16/10]"
							>
								{#if related.featuredImage}
									<img
										src={related.featuredImage.startsWith('http') ? related.featuredImage : `${getImageUrl(related.featuredImage, 600, 375)}&output=webp&quality=80`}
										alt={rTitle}
										class="w-full h-full object-cover hover:scale-105 transition duration-700"
										loading="lazy"
									/>
								{:else}
									<div class="w-full h-full flex items-center justify-center text-4xl bg-slate-50 opacity-30 grayscale">🔭</div>
								{/if}
							</a>
							<div class="p-6 flex flex-col flex-1">
								<a href="/{lang}/artigos/{rSlug}" class="hover:text-primary transition-colors">
									<h3 class="text-xl font-bold text-slate-900 mb-4 line-clamp-2 font-serif leading-tight">
										{rTitle}
									</h3>
								</a>
								<p class="text-slate-500 text-sm line-clamp-2 font-serif mb-6 italic">{rExcerpt}</p>
								<div class="mt-auto pt-6 border-t border-slate-50 text-[10px] font-black uppercase tracking-widest text-slate-400">
									{formatDate(related.publishedAt || related.$createdAt)}
								</div>
							</div>
						</div>
					{/each}
				</div>
			</div>
		</section>
	{/if}
</main>

// apps/web-nuxt/pages/artigos/[slug].vue
<script setup lang="ts">
import { Calendar, Clock, Share2 } from "lucide-vue-next";
import { getImageUrl } from "~/server/utils/appwrite";
import { shouldShowTranslationFallbackBadge } from "~/server/utils/locale";
import { readingTime } from "~/lib/utils";

const { locale, t } = useI18n();
const route = useRoute();
type ArticleDetailsResponse = { article: any; relatedArticles: any[] };

const { data, error } = await useAsyncData<ArticleDetailsResponse>(
  `article-${route.params.slug}-${locale.value}`,
  () =>
    fetch(
      `/api/articles/${route.params.slug}?locale=${encodeURIComponent(locale.value)}`
    ).then((response) => response.json())
);

if (error.value || !data.value?.article) {
  throw createError({ statusCode: 404, statusMessage: "Article not found" });
}

const article = computed(() => data.value?.article as any);
const relatedArticles = computed(() => data.value?.relatedArticles ?? []);
const translation = computed(() => article.value.translation);
const title = computed(
  () => translation.value?.title || article.value.title || ""
);
const excerpt = computed(
  () => translation.value?.excerpt || article.value.excerpt || ""
);
const content = computed(
  () => translation.value?.content || article.value.content || ""
);
const slug = computed(
  () => translation.value?.slug || article.value.slug || route.params.slug
);
const imageUrl = computed(() => {
  if (!article.value.featuredImage) return null;
  return article.value.featuredImage.startsWith("http")
    ? article.value.featuredImage
    : `${getImageUrl(article.value.featuredImage, 1200, 630)}&output=webp&quality=85`;
});
const showFallbackBadge = computed(() =>
  shouldShowTranslationFallbackBadge(locale.value, translation.value)
);

const formattedDate = computed(() =>
  new Date(
    article.value.publishedAt || article.value.$createdAt
  ).toLocaleDateString(locale.value)
);

const siteBase = "https://astrobiologia.com.br";
const localeRouteCodes = ["pt-br", "en", "es", "ja", "nl", "zh"] as const;
const hreflangForCode = (code: string) => {
  if (code === "pt-br") return "pt-BR";
  if (code === "zh") return "zh-Hans";
  return code;
};

const hreflangLinks = computed(() =>
  localeRouteCodes.map((code) => ({
    rel: "alternate" as const,
    href: `${siteBase}${code === "pt-br" ? "" : `/${code}`}/artigos/${slug.value}`,
    hreflang: hreflangForCode(code),
  }))
);

useHead({ link: hreflangLinks });

useSeoMeta({
  title,
  description: excerpt,
  ogTitle: title,
  ogDescription: excerpt,
  ogType: "article",
});

async function shareArticle() {
  if (navigator.share) {
    await navigator.share({
      title: title.value,
      text: excerpt.value,
      url: window.location.href,
    });
  }
}
</script>

<template>
  <main class="min-h-screen bg-background">
    <div
      class="relative overflow-hidden border-b border-slate-100 bg-white pb-16 pt-24 md:pb-24 md:pt-32"
    >
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <span
          v-if="showFallbackBadge"
          class="mb-4 inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700"
          >{{ t("article_missing_locale_badge") }}</span
        >
        <h1
          class="mb-6 text-4xl font-black leading-tight text-slate-900 md:text-6xl"
        >
          {{ title }}
        </h1>
        <p class="mb-10 text-xl italic text-slate-600">{{ excerpt }}</p>
        <div
          class="flex flex-wrap items-center gap-6 text-xs uppercase tracking-widest text-slate-500"
        >
          <span class="flex items-center gap-2"
            ><Calendar class="h-3.5 w-3.5" />{{ formattedDate }}</span
          >
          <span class="flex items-center gap-2"
            ><Clock class="h-3.5 w-3.5" />{{
              t("reading_time", { minutes: readingTime(content) })
            }}</span
          >
        </div>
      </div>
    </div>

    <div v-if="imageUrl" class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
      <img
        :src="imageUrl"
        :alt="article.featuredImageAlt || title"
        class="w-full object-cover"
      />
    </div>

    <article
      class="prose prose-astro mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"
      v-html="content"
    ></article>

    <section
      v-if="relatedArticles.length"
      class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"
    >
      <h2 class="mb-6 text-xl font-bold">{{ t("continue_exploring") }}</h2>
      <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
        <ArticleCard
          v-for="item in relatedArticles"
          :key="item.$id"
          :article="item"
          variant="compact"
        />
      </div>
    </section>

    <div class="mx-auto max-w-3xl px-4 pb-16 sm:px-6 lg:px-8">
      <button
        @click="shareArticle"
        class="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-500 hover:text-primary"
      >
        <Share2 class="h-4 w-4" />{{ t("share") }}
      </button>
    </div>
  </main>
</template>
