// apps/web-nuxt/pages/busca.vue
<script setup lang="ts">
import ArticleCard from "~/components/ArticleCard.vue";

const route = useRoute();
const router = useRouter();
const { locale, t } = useI18n();

const query = ref(typeof route.query.q === "string" ? route.query.q : "");

const { data, refresh } = await useAsyncData(
  () => `search-${locale.value}-${query.value}`,
  () =>
    $fetch("/api/search", { query: { q: query.value, locale: locale.value } })
);

watch(
  () => route.query.q,
  (value) => {
    query.value = typeof value === "string" ? value : "";
    refresh();
  }
);

async function submitSearch() {
  await router.push({ query: query.value ? { q: query.value } : {} });
}

const articles = computed(() => data.value?.articles ?? []);
</script>

<template>
  <main class="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
    <h1 class="text-4xl font-black tracking-tight text-slate-900">
      Busca Global
    </h1>
    <p class="mt-4 text-sm text-slate-600">
      Encontre reportagens por tema, título ou conteúdo.
    </p>

    <form
      class="mt-8 flex flex-col gap-3 sm:flex-row"
      @submit.prevent="submitSearch"
    >
      <input
        v-model="query"
        type="search"
        placeholder="Ex: exoplanetas com água"
        class="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10"
      />
      <button
        type="submit"
        class="rounded-xl bg-primary px-6 py-3 text-xs font-black uppercase tracking-widest text-white hover:bg-primary/90"
      >
        {{ t("search_button") }}
      </button>
    </form>

    <p
      v-if="!query"
      class="mt-6 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"
    >
      Digite um termo para iniciar a busca.
    </p>

    <div v-else class="mt-8 space-y-6">
      <p class="text-sm text-slate-600">
        Resultados para: <strong>{{ query }}</strong> ({{ articles.length }})
      </p>
      <ArticleCard
        v-for="article in articles"
        :key="article.$id"
        :article="article"
      />
    </div>
  </main>
</template>

// src/routes/busca/+page.svelte
<script lang="ts">
	import ArticleCard from '$lib/components/ArticleCard.svelte';
	import { localizeHref } from '$lib/paraglide/runtime';

	let { data } = $props();
	let searchTerm = $state('');

	$effect(() => {
		searchTerm = data.query || '';
	});

	const hasQuery = $derived(searchTerm.trim().length > 0);
	const resultCount = $derived(data.articles.length);
</script>

<svelte:head>
	<title>Busca - Astrobiologia</title>
	<meta
		name="description"
		content="Busque artigos por tema, palavra-chave ou descoberta no portal Astrobiologia."
	/>
	<meta name="robots" content="index, follow" />
</svelte:head>

<main class="min-h-screen bg-slate-50">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<div class="max-w-3xl mx-auto mb-12">
			<h1 class="text-4xl md:text-5xl font-bold text-slate-900 mb-4 text-center">Busca Global</h1>
			<p class="text-xl text-slate-600 font-serif text-center mb-8">
				Encontre artigos por título, resumo e conteúdo.
			</p>

			<form method="GET" action={localizeHref('/busca')} class="flex gap-3">
				<input
					type="search"
					name="q"
					placeholder="Ex.: exoplanetas, biossinais, Marte..."
					bind:value={searchTerm}
					class="flex-1 px-4 py-3 border border-slate-300 rounded-xl focus:ring-2 focus:ring-primary focus:border-transparent outline-none"
				/>
				<button
					type="submit"
					class="px-6 py-3 bg-primary text-primary-foreground rounded-xl hover:bg-primary/90 transition font-semibold"
				>
					Buscar
				</button>
			</form>
		</div>

		{#if hasQuery}
			{#if resultCount > 0}
				<p class="text-sm text-slate-500 mb-8">
					{resultCount} resultado(s) para <strong>"{searchTerm}"</strong>
				</p>
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
					{#each data.articles as article (article.$id)}
						<ArticleCard {article} />
					{/each}
				</div>
			{:else}
				<div class="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-300">
					<p class="text-xl text-slate-600">Nenhum artigo encontrado para "{searchTerm}".</p>
					<p class="text-slate-500 mt-2">Tente outra palavra-chave ou termo mais amplo.</p>
				</div>
			{/if}
		{:else}
			<div class="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-300">
				<p class="text-xl text-slate-600">Digite um termo para iniciar a busca.</p>
			</div>
		{/if}
	</div>
</main>
