// apps/web-nuxt/pages/contato.vue
<template>
  <main class="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
    <h1 class="text-4xl font-black text-slate-900">
      {{ $t("page_contact_title") }}
    </h1>
    <p class="mt-4 text-slate-600">{{ $t("page_contact_intro") }}</p>
    <p class="mt-6 text-sm">
      <strong>{{ $t("page_contact_email_prefix") }}</strong>
      contato@astrobiologia.com.br
    </p>
  </main>
</template>

// src/routes/contato/+page.svelte
<script lang="ts">
    import * as m from '$lib/paraglide/messages';
</script>

<svelte:head>
    <title>Contato - Astrobiologia.com.br</title>
</svelte:head>

<main class="mx-auto max-w-4xl px-4 py-24 sm:px-6 lg:px-8">
    <h1 class="text-4xl font-black text-slate-900 uppercase tracking-tight mb-8">Contato</h1>
    <div class="prose prose-slate max-w-none">
        <p class="text-xl text-slate-600 leading-relaxed font-serif italic mb-8">
            Dúvidas, sugestões ou parcerias? Entre em contato conosco.
        </p>
        <p>Email: danilo.albergaria@gmail.com</p>
    </div>
</main>
