// apps/web-nuxt/pages/artigos/[slug].vue
<script setup lang="ts">
import { Calendar, Clock, Share2 } from "lucide-vue-next";
import { getImageUrl } from "~/server/utils/appwrite";
import { shouldShowTranslationFallbackBadge } from "~/server/utils/locale";
import { readingTime } from "~/lib/utils";

const { locale, t } = useI18n();
const route = useRoute();
type ArticleDetailsResponse = { article: any; relatedArticles: any[] };

const { data, error } = await useAsyncData<ArticleDetailsResponse>(
  `article-${route.params.slug}-${locale.value}`,
  () =>
    fetch(
      `/api/articles/${route.params.slug}?locale=${encodeURIComponent(locale.value)}`
    ).then((response) => response.json())
);

if (error.value || !data.value?.article) {
  throw createError({ statusCode: 404, statusMessage: "Article not found" });
}

const article = computed(() => data.value?.article as any);
const relatedArticles = computed(() => data.value?.relatedArticles ?? []);
const translation = computed(() => article.value.translation);
const title = computed(
  () => translation.value?.title || article.value.title || ""
);
const excerpt = computed(
  () => translation.value?.excerpt || article.value.excerpt || ""
);
const content = computed(
  () => translation.value?.content || article.value.content || ""
);
const slug = computed(
  () => translation.value?.slug || article.value.slug || route.params.slug
);
const imageUrl = computed(() => {
  if (!article.value.featuredImage) return null;
  return article.value.featuredImage.startsWith("http")
    ? article.value.featuredImage
    : `${getImageUrl(article.value.featuredImage, 1200, 630)}&output=webp&quality=85`;
});
const showFallbackBadge = computed(() =>
  shouldShowTranslationFallbackBadge(locale.value, translation.value)
);

const formattedDate = computed(() =>
  new Date(
    article.value.publishedAt || article.value.$createdAt
  ).toLocaleDateString(locale.value)
);

const siteBase = "https://astrobiologia.com.br";
const localeRouteCodes = ["pt-br", "en", "es", "ja", "nl", "zh"] as const;
const hreflangForCode = (code: string) => {
  if (code === "pt-br") return "pt-BR";
  if (code === "zh") return "zh-Hans";
  return code;
};

const hreflangLinks = computed(() =>
  localeRouteCodes.map((code) => ({
    rel: "alternate" as const,
    href: `${siteBase}${code === "pt-br" ? "" : `/${code}`}/artigos/${slug.value}`,
    hreflang: hreflangForCode(code),
  }))
);

useHead({ link: hreflangLinks });

useSeoMeta({
  title,
  description: excerpt,
  ogTitle: title,
  ogDescription: excerpt,
  ogType: "article",
});

async function shareArticle() {
  if (navigator.share) {
    await navigator.share({
      title: title.value,
      text: excerpt.value,
      url: window.location.href,
    });
  }
}
</script>

<template>
  <main class="min-h-screen bg-background">
    <div
      class="relative overflow-hidden border-b border-slate-100 bg-white pb-16 pt-24 md:pb-24 md:pt-32"
    >
      <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <span
          v-if="showFallbackBadge"
          class="mb-4 inline-flex rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700"
          >{{ t("article_missing_locale_badge") }}</span
        >
        <h1
          class="mb-6 text-4xl font-black leading-tight text-slate-900 md:text-6xl"
        >
          {{ title }}
        </h1>
        <p class="mb-10 text-xl italic text-slate-600">{{ excerpt }}</p>
        <div
          class="flex flex-wrap items-center gap-6 text-xs uppercase tracking-widest text-slate-500"
        >
          <span class="flex items-center gap-2"
            ><Calendar class="h-3.5 w-3.5" />{{ formattedDate }}</span
          >
          <span class="flex items-center gap-2"
            ><Clock class="h-3.5 w-3.5" />{{
              t("reading_time", { minutes: readingTime(content) })
            }}</span
          >
        </div>
      </div>
    </div>

    <div v-if="imageUrl" class="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
      <img
        :src="imageUrl"
        :alt="article.featuredImageAlt || title"
        class="w-full object-cover"
      />
    </div>

    <article
      class="prose prose-astro mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8"
      v-html="content"
    ></article>

    <section
      v-if="relatedArticles.length"
      class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"
    >
      <h2 class="mb-6 text-xl font-bold">{{ t("continue_exploring") }}</h2>
      <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
        <ArticleCard
          v-for="item in relatedArticles"
          :key="item.$id"
          :article="item"
          variant="compact"
        />
      </div>
    </section>

    <div class="mx-auto max-w-3xl px-4 pb-16 sm:px-6 lg:px-8">
      <button
        @click="shareArticle"
        class="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-500 hover:text-primary"
      >
        <Share2 class="h-4 w-4" />{{ t("share") }}
      </button>
    </div>
  </main>
</template>

// src/routes/articles/[slug]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import type { PageData } from './$types';

	export let data: PageData;
	const { article, relatedArticles } = data;
</script>

<svelte:head>
	<title>{article.title} - Astrobiologia</title>
	<meta name="description" content={article.description} />
	<meta name="og:title" content={article.title} />
	<meta name="og:description" content={article.description} />
	{#if article.featuredImage}
		<meta name="og:image" content={article.featuredImage} />
	{/if}
	<meta name="article:author" content={article.author || 'Danilo Couto'} />
	<meta name="article:published_time" content={article.publishedAt} />
	<meta name="article:modified_time" content={article.updatedAt} />
	{#each article.tags || [] as tag}
		<meta name="article:tag" content={tag} />
	{/each}
</svelte:head>

<main class="min-h-screen bg-white">
	<!-- Hero Section -->
	{#if article.featuredImage}
		<div class="relative h-96 md:h-[500px] bg-slate-200 overflow-hidden">
			<img
				src={article.featuredImage}
				alt={article.title}
				class="w-full h-full object-cover"
			/>
			<div
				class="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent"
			/>
		</div>
	{/if}

	<!-- Content -->
	<article class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
		<div class="mb-8">
			<div class="flex items-center gap-4 mb-4">
				<span class="inline-block px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">
					{article.category}
				</span>
				<time class="text-slate-600 text-sm">
					{new Date(article.publishedAt).toLocaleDateString('en-US', {
						year: 'numeric',
						month: 'long',
						day: 'numeric'
					})}
				</time>
			</div>
			<h1 class="text-4xl md:text-5xl font-bold text-slate-900 mb-4">
				{article.title}
			</h1>
			<p class="text-xl text-slate-600 mb-6">
				{article.description}
			</p>
			{#if article.author}
				<div class="text-slate-600">
					By <strong>{article.author}</strong>
				</div>
			{/if}
		</div>

		<!-- Article Body -->
		<div class="prose prose-lg max-w-none mb-12">
			{@html article.content}
		</div>

		<!-- Tags -->
		{#if article.tags && article.tags.length > 0}
			<div class="py-8 border-t border-slate-200">
				<h3 class="text-sm font-semibold text-slate-900 mb-4">Tags</h3>
				<div class="flex flex-wrap gap-2">
					{#each article.tags as tag}
						<a
							href="/articles?search={tag}"
							class="px-3 py-1 bg-slate-100 text-slate-700 rounded-full text-sm hover:bg-slate-200 transition"
						>
							{tag}
						</a>
					{/each}
				</div>
			</div>
		{/if}
	</article>

	<!-- Related Articles -->
	{#if relatedArticles && relatedArticles.length > 0}
		<section class="bg-slate-50 py-16">
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
				<h2 class="text-3xl font-bold text-slate-900 mb-12">Related Articles</h2>
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
					{#each relatedArticles as relatedArticle (relatedArticle.$id)}
						<a
							href="/articles/{relatedArticle.slug}"
							class="group block bg-white rounded-lg overflow-hidden shadow hover:shadow-lg transition"
						>
							{#if relatedArticle.featuredImage}
								<div class="h-48 bg-slate-200 overflow-hidden">
									<img
										src={relatedArticle.featuredImage}
										alt={relatedArticle.title}
										class="w-full h-full object-cover group-hover:scale-105 transition duration-300"
									/>
								</div>
							{/if}
							<div class="p-6">
								<h3 class="font-bold text-slate-900 group-hover:text-blue-600 mb-2">
									{relatedArticle.title}
								</h3>
								<p class="text-slate-600 text-sm">{relatedArticle.description}</p>
							</div>
						</a>
					{/each}
				</div>
			</div>
		</section>
	{/if}
</main>

<style>
	:global(.prose) {
		--tw-prose-body: rgb(51, 65, 85);
		--tw-prose-headings: rgb(15, 23, 42);
		--tw-prose-links: rgb(37, 99, 235);
		--tw-prose-code: rgb(51, 65, 85);
	}

	:global(.prose code) {
		background-color: rgb(241, 245, 249);
		border-radius: 0.375rem;
		padding: 0.125rem 0.375rem;
	}

	:global(.prose pre) {
		background-color: rgb(15, 23, 42);
		color: rgb(226, 232, 240);
		border-radius: 0.5rem;
		overflow-x: auto;
	}
</style>
